import React, { useState, useEffect, useCallback } from 'react';
import { FiPlus, FiBarChart2, FiDownload, FiTrash2, FiEye } from 'react-icons/fi';
import { getAll, create, remove } from '../services/api';
import DataTable from '../components/DataTable';
import DetailModal from '../components/DetailModal';
import FormModal from '../components/FormModal';
import ConfirmDialog from '../components/ConfirmDialog';
import LoadingSpinner from '../components/LoadingSpinner';

const formFields = [
  { key: 'title', label: 'Report Title', required: true, placeholder: 'Report title' },
  { key: 'type', label: 'Report Type', type: 'select', required: true, options: [
    { value: 'equipment_summary', label: 'Equipment Summary' },
    { value: 'maintenance_history', label: 'Maintenance History' },
    { value: 'cost_analysis', label: 'Cost Analysis' },
    { value: 'failure_analysis', label: 'Failure Analysis' },
    { value: 'sensor_data', label: 'Sensor Data' },
    { value: 'health_assessment', label: 'Health Assessment' },
    { value: 'work_orders', label: 'Work Orders' },
    { value: 'inventory', label: 'Inventory Status' },
  ]},
  { key: 'description', label: 'Description', type: 'textarea' },
  { key: 'dateRange', label: 'Date Range', type: 'select', options: [
    { value: 'last_7_days', label: 'Last 7 Days' }, { value: 'last_30_days', label: 'Last 30 Days' },
    { value: 'last_90_days', label: 'Last 90 Days' }, { value: 'last_year', label: 'Last Year' },
    { value: 'all_time', label: 'All Time' },
  ]},
];

const detailFields = [
  { key: 'title', label: 'Title' },
  { key: 'type', label: 'Type', render: v => <span style={{ textTransform: 'capitalize' }}>{(v || '').replace(/_/g, ' ')}</span> },
  { key: 'description', label: 'Description' },
  { key: 'dateRange', label: 'Date Range', render: v => <span style={{ textTransform: 'capitalize' }}>{(v || '').replace(/_/g, ' ')}</span> },
  { key: 'status', label: 'Status', render: v => (
    <span style={{
      padding: '4px 12px', borderRadius: 12, fontSize: 12, fontWeight: 600,
      backgroundColor: v === 'completed' ? '#00e67618' : '#ffc10718',
      color: v === 'completed' ? '#00e676' : '#ffc107',
    }}>
      {v || 'generated'}
    </span>
  )},
  { key: 'generated_by', label: 'Generated By' },
  { key: 'created_at', label: 'Generated At', render: v => v ? new Date(v).toLocaleString() : '-' },
];

const Reports = () => {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null);
  const [showDetail, setShowDetail] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(null);

  const loadData = useCallback(async () => {
    try {
      const res = await getAll('reports');
      const items = res.data.data || res.data || [];
      setData(Array.isArray(items) ? items : []);
    } catch (err) { console.error(err); } finally { setLoading(false); }
  }, []);

  useEffect(() => { loadData(); }, [loadData]);

  const handleRowClick = (row) => { setSelected(row); setShowDetail(true); };
  const handleDelete = (item) => { setShowDetail(false); setConfirmDelete(item); };

  const handleSubmit = async (formData) => {
    await create('reports', { ...formData, status: 'completed' });
    setShowForm(false);
    loadData();
  };

  const handleConfirmDelete = async () => {
    await remove('reports', confirmDelete.id);
    setConfirmDelete(null);
    loadData();
  };

  const columns = [
    { header: 'Title', accessor: 'title', key: 'title' },
    { header: 'Type', accessor: 'type', key: 'type', render: v => <span style={{ textTransform: 'capitalize' }}>{(v || '').replace(/_/g, ' ')}</span> },
    { header: 'Status', accessor: 'status', key: 'status', render: v => (
      <span style={{
        padding: '3px 10px', borderRadius: 12, fontSize: 11, fontWeight: 600,
        backgroundColor: v === 'completed' ? '#00e67618' : '#ffc10718',
        color: v === 'completed' ? '#00e676' : '#ffc107',
      }}>
        {v || 'generated'}
      </span>
    )},
    { header: 'Generated', accessor: 'created_at', key: 'created_at', render: v => v ? new Date(v).toLocaleDateString() : '-' },
    { header: 'Actions', key: 'actions', accessor: () => null, render: (_, row) => (
      <div style={{ display: 'flex', gap: 8 }} onClick={e => e.stopPropagation()}>
        <button
          onClick={() => { setSelected(row); setShowDetail(true); }}
          style={{
            padding: '4px 8px', borderRadius: 6, border: '1px solid #1a73e8',
            backgroundColor: 'transparent', color: '#1a73e8', cursor: 'pointer',
            display: 'flex', alignItems: 'center', gap: 4, fontSize: 12,
          }}
        >
          <FiEye size={12} /> View
        </button>
        <button
          onClick={() => setConfirmDelete(row)}
          style={{
            padding: '4px 8px', borderRadius: 6, border: '1px solid #ff5252',
            backgroundColor: 'transparent', color: '#ff5252', cursor: 'pointer',
            display: 'flex', alignItems: 'center', gap: 4, fontSize: 12,
          }}
        >
          <FiTrash2 size={12} /> Delete
        </button>
      </div>
    )},
  ];

  if (loading) return <LoadingSpinner />;

  return (
    <div>
      <div className="page-header">
        <div>
          <div className="page-title"><FiBarChart2 style={{ marginRight: 10 }} />Reports</div>
          <div className="page-subtitle">{data.length} reports generated</div>
        </div>
        <button className="btn-primary" onClick={() => setShowForm(true)}><FiPlus size={16} /> Generate Report</button>
      </div>

      <DataTable columns={columns} data={data} onRowClick={handleRowClick} />

      <DetailModal
        open={showDetail} title={selected?.title || 'Report Details'}
        data={selected || {}} fields={detailFields}
        onClose={() => setShowDetail(false)} onDelete={handleDelete}
      />

      <FormModal
        open={showForm} title="Generate Report"
        fields={formFields} initialData={{}}
        onSubmit={handleSubmit} onClose={() => setShowForm(false)}
        submitText="Generate"
      />

      <ConfirmDialog
        open={!!confirmDelete} title="Delete Report"
        message={`Delete report "${confirmDelete?.title}"?`}
        onConfirm={handleConfirmDelete} onCancel={() => setConfirmDelete(null)}
      />
    </div>
  );
};

export default Reports;
