module.exports={
 caseType:'operator_approved_maintenance_dispatch',initialState:'asset_registered',
 states:['asset_registered','sources_synchronized','constraints_validated','forecast_recorded','operator_review','dispatch_approved','execution_observed','exception_recovery','outcome_recorded','manual_fallback'],
 createRoles:['reliability_engineer','maintenance_manager'],assessmentRoles:['reliability_engineer','operator','safety_reviewer','planner'],auditRoles:['maintenance_manager','safety_reviewer','auditor'],connectorRoles:['integration_operator','maintenance_manager'],
 evidenceKinds:['asset_version','job_snapshot','telemetry_batch_digest','sensor_quality_report','cmms_erp_snapshot','scada_snapshot','gis_weather_snapshot','constraint_manifest','model_version','historical_replay_report','forecast_manifest','operator_review','dispatch_approval','execution_feedback','exception_record','realized_outcome','asset_lifecycle_record'],
 requiredSignals:['assetVersion','jobVersion','telemetryVersion','modelVersion','constraintVersion','sourceTimestamp','evaluatedAt','staleAfterSeconds','forecastErrorBound','constraintViolationRate','offlineBufferComplete','safetyLimitsVerified','historicalReplayStatus','policyVersion'],
 professionalBoundary:'Maintenance forecasts and dispatch suggestions are advisory; they cannot operate equipment, bypass SCADA/safety systems, dispatch personnel, or replace qualified operators and maintenance planners.',
 connectors:[{name:'telemetry',purpose:'timestamped read-only sensor batches'},{name:'erp_wms_tms',purpose:'jobs materials and logistics snapshots'},{name:'scada',purpose:'read-only asset and alarm references'},{name:'gis_weather',purpose:'site conditions'},{name:'cmms_asset_management',purpose:'asset lifecycle and work-order receipts'},{name:'notification',purpose:'operator acknowledgement receipts'},{name:'device_gateway',purpose:'offline buffer and delivery receipts'}],
 transitions:[
  {from:'asset_registered',action:'synchronize_sources',to:'sources_synchronized',roles:['integration_operator','reliability_engineer'],requiresEvidence:true},
  {from:'sources_synchronized',action:'validate_constraints',to:'constraints_validated',roles:['reliability_engineer','safety_reviewer'],requiresEvidence:true},
  {from:'constraints_validated',action:'record_forecast',to:'forecast_recorded',roles:['reliability_engineer'],requiresEvidence:true},
  {from:'forecast_recorded',action:'submit_operator_review',to:'operator_review',roles:['operator','planner','safety_reviewer'],requiresEvidence:true,dualControl:true},
  {from:'operator_review',action:'approve_dispatch',to:'dispatch_approved',roles:['maintenance_manager'],requiresEvidence:true,dualControl:true},
  {from:'dispatch_approved',action:'record_execution_observation',to:'execution_observed',roles:['operator','integration_operator'],requiresEvidence:true},
  {from:'execution_observed',action:'open_exception',to:'exception_recovery',roles:['operator','safety_reviewer'],requiresEvidence:true},
  {from:'exception_recovery',action:'manual_fallback',to:'manual_fallback',roles:['maintenance_manager','safety_reviewer'],requiresEvidence:true,dualControl:true},
  {from:'execution_observed',action:'record_outcome',to:'outcome_recorded',roles:['reliability_engineer','planner'],requiresEvidence:true,dualControl:true},
  {from:'exception_recovery',action:'record_outcome',to:'outcome_recorded',roles:['maintenance_manager'],requiresEvidence:true,dualControl:true}
 ],
 acceptedFixture:{assetVersion:'a1',jobVersion:'j1',telemetryVersion:'t1',modelVersion:'m1',constraintVersion:'c1',sourceTimestamp:'2026-07-18T10:00:00Z',evaluatedAt:'2026-07-18T10:01:00Z',staleAfterSeconds:300,forecastErrorBound:0.08,constraintViolationRate:0,offlineBufferComplete:true,safetyLimitsVerified:true,historicalReplayStatus:'passed',policyVersion:'p1'},
 readyDisposition:'operator_dispatch_review_required',holdDisposition:'manual_maintenance_fallback',decisionField:'dispatchCommand',
 assess:x=>{const source=Date.parse(x.sourceTimestamp),evaluated=Date.parse(x.evaluatedAt),limit=Number(x.staleAfterSeconds),error=Number(x.forecastErrorBound),violations=Number(x.constraintViolationRate);const stale=!Number.isFinite(source)||!Number.isFinite(evaluated)||!Number.isFinite(limit)||limit<=0||evaluated<source||(evaluated-source)/1000>limit;const metrics=Number.isFinite(error)&&error>=0&&error<=1&&Number.isFinite(violations)&&violations>=0&&violations<=1;const ready=!stale&&metrics&&error<=0.15&&violations===0&&x.offlineBufferComplete===true&&x.safetyLimitsVerified===true&&x.historicalReplayStatus==='passed';return{disposition:ready?'operator_dispatch_review_required':'manual_maintenance_fallback',dispatchCommand:null,controlCommand:null,stale,metrics:{forecastErrorBound:metrics?error:null,constraintViolationRate:metrics?violations:null},versions:{asset:x.assetVersion,job:x.jobVersion,telemetry:x.telemetryVersion,model:x.modelVersion,constraints:x.constraintVersion}};}
};
